version: '3.7'
services:
  kong-database:
    image: postgres:9.6
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
    ports:
      - 5432:5432
    networks:
      - kong-network

  kong-migrations:
    image: kong:0.14.1-alpine
    container_name: kong-migrations
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
    networks:
      - kong-network
    command: >
      /bin/sh -c "sleep 5s; kong migrations up"

  kong:
    image: kong:0.14.1-alpine
    container_name: kong
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - 8000:8000
      - 8001:8001
    depends_on:
      - kong-migrations
    networks:
      - kong-network
    command: >
      /bin/sh -c "sleep 10s; kong start"

networks:
  kong-network:
    driver: bridge